// apps/showcase/src/shared/LoadingSkeleton/host-react.tsx
// host-react.tsx —— 函数组件,渲染 LoadingSkeleton 到挂载点,
// 通过 forwardRef 暴露 appear / fadeOut / destroy。

import * as React from 'react';
import { forwardRef, useImperativeHandle, useRef, useState } from 'react';

// * as React 引入是为了让 classic JSX 运行时 (`React.createElement`) 在
// showcase 的 .tsx 编译环境下找到 React —— showcase tsconfig 用 jsx: preserve
// 而非 react-jsx(esbuild 默认转 classic)。React 在内部不被代码直接引用,
// 但 JSX 编译后会在文件顶层读 `React.createElement`,所以 ESLint 不会报
// 未用局部(它知道这个 import 是给 JSX runtime 用的)。

export interface LoadingSkeletonRef {
  appear(): Promise<void>;
  fadeOut(onFaded?: () => void): Promise<void>;
  destroy(): void;
}

interface Props {
  className?: string;
}

export const LoadingSkeleton = forwardRef<LoadingSkeletonRef, Props>(function LoadingSkeleton(
  { className },
  ref,
) {
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [opacity, setOpacity] = useState(0);
  const destroyedRef = useRef(false);

  function setOp(target: 0 | 1): Promise<void> {
    return new Promise((resolve) => {
      const el = rootRef.current;
      if (!el) return resolve();
      // 强制 reflow,确保 transition 生效(连续 appear/fadeOut 不叠加)
      void el.offsetHeight;
      setOpacity(target);
      const onEnd = () => {
        el.removeEventListener('transitionend', onEnd);
        resolve();
      };
      el.addEventListener('transitionend', onEnd);
      // 兜底:transitionend 不触发(浏览器降级/disabled)时,650ms 后强制 resolve
      setTimeout(onEnd, 650);
    });
  }

  useImperativeHandle(
    ref,
    () => ({
      appear(): Promise<void> {
        if (destroyedRef.current) return Promise.resolve();
        return setOp(1);
      },
      fadeOut(onFaded?: () => void): Promise<void> {
        if (destroyedRef.current) {
          onFaded?.();
          return Promise.resolve();
        }
        return setOp(0).then(() => {
          if (rootRef.current?.parentNode) rootRef.current.parentNode.removeChild(rootRef.current);
          destroyedRef.current = true;
          onFaded?.();
        });
      },
      destroy(): void {
        if (destroyedRef.current) return;
        destroyedRef.current = true;
        if (rootRef.current?.parentNode) rootRef.current.parentNode.removeChild(rootRef.current);
      },
    }),
    [],
  );

  return (
    <div
      ref={rootRef}
      className={className ?? 'sl-skel'}
      style={{ opacity, transition: 'opacity 600ms ease' }}
      role="status"
      aria-live="polite"
    >
      <div className="sl-skel__spinner" />
      <div className="sl-skel__text">加载中…</div>
      <div className="sl-skel__bars">
        <div className="sl-skel__bar sl-skel__bar--title" />
        <div className="sl-skel__bar" />
        <div className="sl-skel__bar" />
      </div>
    </div>
  );
});

// apps/showcase/src/shared/LoadingSkeleton/host-vue.vue
<!--
  host-vue.vue —— Vue 3 SFC,渲染 LoadingSkeleton 到挂载点,
  通过 defineExpose 暴露 appear / fadeOut / destroy 给父。
-->
<template>
  <div
    ref="root"
    :class="className"
    :style="{ opacity: visible ? 1 : 0, transition: 'opacity 600ms ease' }"
    role="status"
    aria-live="polite"
  >
    <div class="sl-skel__spinner" />
    <div class="sl-skel__text">
      加载中…
    </div>
    <div class="sl-skel__bars">
      <div class="sl-skel__bar sl-skel__bar--title" />
      <div class="sl-skel__bar" />
      <div class="sl-skel__bar" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

defineProps<{
  className?: string;
}>();

const root = ref<HTMLDivElement | null>(null);
const visible = ref(0); // 0 / 1,绑定 opacity
let destroyed = false;

function setOpacity(target: 0 | 1): Promise<void> {
  return new Promise((resolve) => {
    const el = root.value;
    if (!el) return resolve();
    // 强制 reflow,确保 transition 生效(连续 appear/fadeOut 不叠加)
    void el.offsetHeight;
    visible.value = target;
    const onEnd = () => {
      el.removeEventListener('transitionend', onEnd);
      resolve();
    };
    el.addEventListener('transitionend', onEnd);
    // 兜底:transitionend 不触发(浏览器降级/disabled)时,650ms 后强制 resolve
    setTimeout(onEnd, 650);
  });
}

defineExpose({
  appear(): Promise<void> {
    if (destroyed) return Promise.resolve();
    return setOpacity(1);
  },
  fadeOut(onFaded?: () => void): Promise<void> {
    if (destroyed) {
      onFaded?.();
      return Promise.resolve();
    }
    return setOpacity(0).then(() => {
      if (root.value?.parentNode) root.value.parentNode.removeChild(root.value);
      destroyed = true;
      onFaded?.();
    });
  },
  destroy(): void {
    if (destroyed) return;
    destroyed = true;
    if (root.value?.parentNode) root.value.parentNode.removeChild(root.value);
  },
});
</script>
